"""Write gold out as vault markdown so the ontology stays readable outside the app.

Files are generated: hand edits are overwritten, and scoping never treats them
as artefacts (`type: ontology`)."""
from __future__ import annotations

import os
import tempfile
from pathlib import Path

import frontmatter

from ghostbrain.api.repo import projects as projects_repo
from ghostbrain.ontology.graph import GraphUnavailable
from ghostbrain.ontology.schema import ui_kind
from ghostbrain.paths import vault_path

HEADER = "<!-- Generated by Poltergeist from the ratified ontology. Edits are overwritten. -->"


def ontology_dir_for(project: dict) -> Path:
    return vault_path() / projects_repo.PROJECT_DIR_TEMPLATE.format(
        context=project["context"], slug=project["slug"]) / "ontology"


def generated_note_path(project: dict, node: dict) -> str:
    """Vault-relative POSIX path of a domain node's generated note."""
    from ghostbrain.api.repo.notes_manual import make_slug  # noqa: PLC0415 (import cycle)

    rel = f"{ui_kind(node['kind'])}/{node['uid'][:8]}-{make_slug(node['name']) or 'node'}.md"
    return (ontology_dir_for(project) / rel).relative_to(vault_path()).as_posix()


def _atomic_write(path: Path, text: str) -> None:
    """Write via a temp file; skip when the bytes are unchanged (no mtime churn)."""
    data = text.encode("utf-8")
    try:
        if path.read_bytes() == data:
            return
    except OSError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "wb") as f:  # bytes: the comparison above is exact on every OS
            f.write(data)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def _wikilink(rel_path: str | None, fallback: str) -> str:
    if not rel_path:
        return fallback
    return f"[[{rel_path[:-3] if rel_path.endswith('.md') else rel_path}]]"


def _text(value) -> str | None:
    """Graph temporals come back as Java objects; YAML needs plain strings."""
    return None if value is None else str(value)


def write_project(graph, project_uuid: str) -> int:
    project = projects_repo.get_project_by_uuid(project_uuid)
    if project is None:
        return 0
    root = ontology_dir_for(project)
    nodes = graph.project_export(project_uuid)
    vault = vault_path()
    rel_of = {n["uid"]: (vault / generated_note_path(project, n)).relative_to(root).as_posix() for n in nodes}
    keep: set[Path] = set()
    for n in nodes:
        path = root / rel_of[n["uid"]]
        keep.add(path)
        lines = [HEADER, f"# {n['name']}", "", n.get("statement") or ""]
        if n.get("value"):
            lines += ["", f"**Value:** {n['value']}"]
        if n["evidence"]:
            lines += ["", "## Evidence"]
            lines += [f"- {_wikilink(e['note_path'], e['title'] or '?')} — \"{e['quote']}\"" for e in n["evidence"]]
        if n["relations"]:
            lines += ["", "## Related"]
            for r in n["relations"]:
                target = rel_of.get(r["target_uid"])
                link = _wikilink((root / target).relative_to(vault).as_posix(), r["target_name"] or "?") \
                    if target else (r["target_name"] or r["target_uid"])
                lines.append(f"- {r['type']} → {link}")
        post = frontmatter.Post("\n".join(lines) + "\n", type="ontology", ontologyKind=ui_kind(n["kind"]),
                                uuid=n["uid"], project=project_uuid, ratifiedAt=_text(n.get("valid_from")),
                                provenance=_text(n.get("provenance")), generated=True)
        _atomic_write(path, frontmatter.dumps(post) + "\n")
    if root.exists():
        for old in root.rglob("*.md"):
            if old in keep:
                continue
            try:
                if frontmatter.load(old).get("generated") is True:
                    old.unlink()
            except Exception:  # noqa: BLE001 - never delete what we cannot identify as ours
                continue
    return len(nodes)


def on_applied(svc, project_uuids: list[str]) -> None:
    enabled = {p["project_uuid"] for p in svc.store.enabled_projects()}
    targets = [p for p in project_uuids if p in enabled or projects_repo.get_project_by_uuid(p)]
    if not targets:
        return
    try:
        with svc.graph_session() as g:
            for p in targets:
                write_project(g, p)
    except GraphUnavailable:
        return
