"""Per-project CLAUDE.md generation. See SPEC §7.3.

Stitches together the profile layer (working-style, preferences, current-projects
filtered to the project's context, plus the recent layer) and writes a CLAUDE.md
file at the project root. Claude Code picks it up automatically on session start.

CLI:
    python -m ghostbrain.profile.claude_md <project_path>
    python -m ghostbrain.profile.claude_md --all     # regen for every project under configured roots
"""

from __future__ import annotations

import argparse
import logging
import re
from pathlib import Path

import yaml

from ghostbrain.paths import vault_path

log = logging.getLogger("ghostbrain.profile.claude_md")

CLAUDE_MD_HEADER = (
    "<!-- Auto-generated by ghostbrain. Do not hand-edit; "
    "changes will be overwritten by the nightly regen.\n"
    "To change content, edit files under vault/80-profile/. -->\n"
)


def detect_context(project_path: Path, routing: dict | None = None) -> str | None:
    """Return the context for this project path by longest-prefix match.

    Looks at ``claude_code.project_paths`` in ``routing.yaml``. Returns ``None`` if
    no rule matches — the caller decides what to do (typically: skip context-specific
    sections, still emit the universal profile).
    """
    if routing is None:
        routing = _load_routing()
    rules: dict[str, str] = (routing.get("claude_code") or {}).get("project_paths") or {}
    if not rules:
        return None

    project_str = str(project_path.expanduser().resolve())
    best: tuple[int, str] | None = None
    for prefix, ctx in rules.items():
        prefix_resolved = str(Path(prefix).expanduser())
        if project_str == prefix_resolved or project_str.startswith(prefix_resolved + "/"):
            if best is None or len(prefix_resolved) > best[0]:
                best = (len(prefix_resolved), ctx)
    return best[1] if best else None


def filter_by_context(content: str, context: str) -> str:
    """Extract the section under ``## {context}`` (case-insensitive) from the document.

    Returns just that section's heading + body. If no matching section, returns ''.
    The match is on the immediate H2 heading text, normalized (lowercased, trimmed).
    """
    if not content or not context:
        return ""

    target = context.strip().lower()
    lines = content.splitlines()
    out: list[str] = []
    inside = False

    for line in lines:
        m = re.match(r"^(#{1,6})\s+(.*?)\s*$", line)
        if m:
            level = len(m.group(1))
            heading = m.group(2).strip().lower()
            if level == 2:
                if heading == target:
                    inside = True
                    out.append(line)
                    continue
                if inside:
                    break
            elif level == 1 and inside:
                # H1 ends any H2 section as well.
                break
        if inside:
            out.append(line)

    return "\n".join(out).rstrip() + ("\n" if out else "")


def generate_claude_md(project_path: Path, *, routing: dict | None = None) -> Path:
    """Build the CLAUDE.md content from vault/80-profile + per-context profile.

    Returns the path written. Overwrites any existing CLAUDE.md.
    """
    project_path = project_path.expanduser().resolve()
    vault = vault_path()
    routing = routing or _load_routing()
    context = detect_context(project_path, routing)

    profile = vault / "80-profile"
    parts: list[str] = [CLAUDE_MD_HEADER]

    parts.append(_read(profile / "working-style.md"))
    parts.append(_read(profile / "preferences.md"))

    if context is not None:
        parts.append(_read(vault / "20-contexts" / context / "_profile.md"))

    current_projects = _read(profile / "current-projects.md")
    if context is not None:
        filtered = filter_by_context(current_projects, context)
        if filtered:
            parts.append(filtered)
        else:
            parts.append(current_projects)
    else:
        parts.append(current_projects)

    parts.append(_read(profile / "_recent.md"))

    body = "\n\n".join(p for p in parts if p.strip())
    out = project_path / "CLAUDE.md"
    out.write_text(body, encoding="utf-8")
    log.info("Wrote %s (context=%s)", out, context)
    return out


def regenerate_all(roots: list[Path] | None = None) -> list[Path]:
    """Regenerate CLAUDE.md for every project under each configured root.

    A "project" is any direct child directory containing one of the marker files
    (``package.json``, ``pyproject.toml``, ``Cargo.toml``, ``go.mod``, ``.git``).
    """
    roots = roots or _configured_project_roots()
    routing = _load_routing()
    written: list[Path] = []
    for root in roots:
        root = root.expanduser()
        if not root.exists():
            log.info("Project root %s does not exist; skipping", root)
            continue
        for child in sorted(root.iterdir()):
            if not child.is_dir():
                continue
            if not _looks_like_project(child):
                continue
            written.append(generate_claude_md(child, routing=routing))
    return written


def _looks_like_project(path: Path) -> bool:
    markers = ("package.json", "pyproject.toml", "Cargo.toml", "go.mod", ".git")
    return any((path / m).exists() for m in markers)


def _read(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8").strip()


def _load_routing() -> dict:
    f = vault_path() / "90-meta" / "routing.yaml"
    if not f.exists():
        return {}
    return yaml.safe_load(f.read_text(encoding="utf-8")) or {}


def _load_config() -> dict:
    f = vault_path() / "90-meta" / "config.yaml"
    if not f.exists():
        return {}
    return yaml.safe_load(f.read_text(encoding="utf-8")) or {}


def _configured_project_roots() -> list[Path]:
    cfg = _load_config()
    raw = (cfg.get("profile") or {}).get("project_roots") or ["~/code", "~/development"]
    return [Path(p) for p in raw]


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate per-project CLAUDE.md files.")
    parser.add_argument("project", nargs="?",
                        help="Path to a single project. Omit when using --all.")
    parser.add_argument("--all", action="store_true",
                        help="Regenerate for every project under configured roots.")
    args = parser.parse_args()

    if not args.all and not args.project:
        parser.error("provide a project path, or pass --all")
    if args.all and args.project:
        parser.error("project path and --all are mutually exclusive")

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if args.all:
        written = regenerate_all()
        print(f"Wrote {len(written)} CLAUDE.md file(s).")
        for p in written:
            print(f"  {p}")
    else:
        out = generate_claude_md(Path(args.project))
        print(f"Wrote {out}")


if __name__ == "__main__":
    main()
