import { TopBar } from '../components/TopBar';
import { Panel } from '../components/Panel';
import { SkeletonRows } from '../components/SkeletonRows';
import { PanelEmpty } from '../components/PanelEmpty';
import { PanelError } from '../components/PanelError';
import { Eyebrow } from '../components/Eyebrow';
import { useDaily } from '../lib/api/hooks';
import { useNoteView } from '../stores/note-view';
import type { DailyDigest } from '../../shared/api-types';

export function DailyScreen() {
  const daily = useDaily({ limit: 100 });
  const openNote = useNoteView((s) => s.open);

  const openDigest = (date: string) => openNote(`10-daily/${date}.md`);

  return (
    <div className="flex-1 overflow-y-auto bg-paper">
      <TopBar
        title="daily"
        subtitle={daily.data ? `${daily.data.total} digests in vault` : '…'}
      />
      <div className="max-w-[900px] px-8 py-6">
        <Panel title="recent digests" subtitle="generated by the worker · newest first">
          {daily.isLoading && <SkeletonRows count={4} />}
          {daily.isError && (
            <PanelError
              message={
                daily.error instanceof Error ? daily.error.message : 'failed to load digests'
              }
              onRetry={() => daily.refetch()}
            />
          )}
          {daily.data && daily.data.items.length === 0 && (
            <PanelEmpty icon="calendar" message="no daily digests yet" />
          )}
          {daily.data && daily.data.items.length > 0 && (
            <>
              <div
                className="grid gap-3 border-b border-hairline px-2 pb-2 pt-1"
                style={{ gridTemplateColumns: '120px minmax(0, 1fr) 60px' }}
              >
                <Eyebrow>date</Eyebrow>
                <Eyebrow>summary</Eyebrow>
                <Eyebrow>notes</Eyebrow>
              </div>
              {daily.data.items.map((d) => (
                <DigestRow key={d.id} d={d} onOpen={() => openDigest(d.date)} />
              ))}
            </>
          )}
        </Panel>
      </div>
    </div>
  );
}

function DigestRow({ d, onOpen }: { d: DailyDigest; onOpen: () => void }) {
  return (
    <button
      type="button"
      onClick={onOpen}
      className="grid w-full cursor-pointer items-start gap-3 rounded-sm bg-transparent px-2 py-[10px] text-left hover:bg-paper"
      style={{ gridTemplateColumns: '120px minmax(0, 1fr) 60px' }}
    >
      <span className="font-mono text-11 text-ink-2">{d.date}</span>
      <span className="text-13 leading-[1.5] text-ink-1">{d.snippet || d.title}</span>
      <span className="text-right font-mono text-11 text-ink-2">{d.noteCount}</span>
    </button>
  );
}
