"""Unit tests for the CLAUDE.md generator (Phase 2)."""

from __future__ import annotations

import importlib
from pathlib import Path

import pytest


@pytest.fixture()
def vault(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.setenv("VAULT_PATH", str(tmp_path))
    import ghostbrain.paths as _paths
    importlib.reload(_paths)
    import ghostbrain.profile.claude_md as cm
    importlib.reload(cm)
    # Bootstrap a minimal vault.
    from ghostbrain.bootstrap import bootstrap
    bootstrap(tmp_path)
    return tmp_path


def _routing_with(rules: dict[str, str]) -> dict:
    return {"claude_code": {"project_paths": rules}}


def test_detect_context_returns_match(vault: Path) -> None:
    from ghostbrain.profile.claude_md import detect_context
    routing = _routing_with({str(vault / "projects" / "my-project"): "codeship"})
    ctx = detect_context(vault / "projects" / "my-project", routing=routing)
    assert ctx == "codeship"


def test_detect_context_handles_subdirectory(vault: Path) -> None:
    from ghostbrain.profile.claude_md import detect_context
    routing = _routing_with({str(vault / "dev" / "sanlam"): "sanlam"})
    ctx = detect_context(vault / "dev" / "sanlam" / "service-x", routing=routing)
    assert ctx == "sanlam"


def test_detect_context_longest_prefix_wins(vault: Path) -> None:
    from ghostbrain.profile.claude_md import detect_context
    routing = _routing_with({
        str(vault / "dev"): "personal",
        str(vault / "dev" / "sanlam"): "sanlam",
    })
    ctx = detect_context(vault / "dev" / "sanlam" / "service-x", routing=routing)
    assert ctx == "sanlam"


def test_detect_context_no_match_returns_none(vault: Path) -> None:
    from ghostbrain.profile.claude_md import detect_context
    routing = _routing_with({str(vault / "nope"): "personal"})
    ctx = detect_context(vault / "elsewhere", routing=routing)
    assert ctx is None


def test_detect_context_does_not_match_partial_segment(vault: Path) -> None:
    """``/dev/sanlam-foo`` must NOT match a rule for ``/dev/sanlam``."""
    from ghostbrain.profile.claude_md import detect_context
    routing = _routing_with({str(vault / "dev" / "sanlam"): "sanlam"})
    ctx = detect_context(vault / "dev" / "sanlam-foo", routing=routing)
    assert ctx is None


def test_filter_by_context_extracts_only_target_section() -> None:
    from ghostbrain.profile.claude_md import filter_by_context
    body = (
        "# Current projects\n\n"
        "## sanlam\n"
        "- ASCP work\n"
        "- DLQ triage\n\n"
        "## codeship\n"
        "- Hive\n"
        "- Ghost Brain\n\n"
        "## personal\n"
        "- cooking\n"
    )
    sanlam = filter_by_context(body, "sanlam")
    codeship = filter_by_context(body, "codeship")

    assert "ASCP work" in sanlam
    assert "DLQ triage" in sanlam
    assert "Hive" not in sanlam
    assert "cooking" not in sanlam

    assert "Hive" in codeship
    assert "Ghost Brain" in codeship
    assert "ASCP work" not in codeship


def test_filter_by_context_case_insensitive() -> None:
    from ghostbrain.profile.claude_md import filter_by_context
    body = "## Sanlam\n- thing\n\n## codeship\n- other\n"
    out = filter_by_context(body, "sanlam")
    assert "thing" in out


def test_filter_by_context_missing_section_returns_empty() -> None:
    from ghostbrain.profile.claude_md import filter_by_context
    body = "## codeship\n- only one section\n"
    assert filter_by_context(body, "sanlam") == ""


def test_generate_claude_md_writes_full_profile(vault: Path, tmp_path: Path) -> None:
    from ghostbrain.profile.claude_md import generate_claude_md

    project = tmp_path / "project-x"
    project.mkdir()
    (project / "package.json").write_text('{"name": "x"}')

    routing = _routing_with({str(project): "codeship"})

    # Replace placeholder profile content with concrete sections so we can
    # assert their presence.
    (vault / "80-profile" / "working-style.md").write_text(
        "# Working style\nDirect, terse.\n"
    )
    (vault / "80-profile" / "preferences.md").write_text(
        "# Preferences\nNo emoji.\n"
    )
    (vault / "80-profile" / "current-projects.md").write_text(
        "# Current projects\n\n## sanlam\n- Ascp\n\n## codeship\n- Hive\n"
    )
    (vault / "20-contexts" / "codeship" / "_profile.md").write_text(
        "# Codeship profile\nShip CLI is canonical.\n"
    )

    out = generate_claude_md(project, routing=routing)
    body = out.read_text()

    assert out == project / "CLAUDE.md"
    assert "Direct, terse." in body
    assert "No emoji." in body
    assert "Ship CLI is canonical." in body
    assert "Hive" in body
    # The other context's projects must not leak in.
    assert "Ascp" not in body
    # Auto-generated header is present.
    assert "Auto-generated by ghostbrain" in body


def test_generate_claude_md_falls_back_when_no_context(vault: Path, tmp_path: Path) -> None:
    """If routing has no rule for the project, full current-projects is emitted
    and the per-context _profile.md is skipped."""
    from ghostbrain.profile.claude_md import generate_claude_md

    project = tmp_path / "elsewhere"
    project.mkdir()

    (vault / "80-profile" / "current-projects.md").write_text(
        "# Current projects\n\n## sanlam\n- A\n\n## codeship\n- B\n"
    )

    out = generate_claude_md(project, routing={"claude_code": {"project_paths": {}}})
    body = out.read_text()

    assert "## sanlam" in body
    assert "## codeship" in body
