"""Unit tests for the CLAUDE.md generator (Phase 2). Uses the shared `vault`
fixture in conftest.py."""

from __future__ import annotations

from pathlib import Path

import pytest


def _routing_with(rules: dict[str, str]) -> dict:
    return {"claude_code": {"project_paths": rules}}


def test_detect_context_returns_match(vault: Path) -> None:
    from ghostbrain.profile.claude_md import detect_context
    routing = _routing_with({str(vault / "projects" / "my-project"): "consulting"})
    ctx = detect_context(vault / "projects" / "my-project", routing=routing)
    assert ctx == "consulting"


def test_detect_context_handles_subdirectory(vault: Path) -> None:
    from ghostbrain.profile.claude_md import detect_context
    routing = _routing_with({str(vault / "dev" / "work"): "work"})
    ctx = detect_context(vault / "dev" / "work" / "service-x", routing=routing)
    assert ctx == "work"


def test_detect_context_longest_prefix_wins(vault: Path) -> None:
    from ghostbrain.profile.claude_md import detect_context
    routing = _routing_with({
        str(vault / "dev"): "personal",
        str(vault / "dev" / "work"): "work",
    })
    ctx = detect_context(vault / "dev" / "work" / "service-x", routing=routing)
    assert ctx == "work"


def test_detect_context_no_match_returns_none(vault: Path) -> None:
    from ghostbrain.profile.claude_md import detect_context
    routing = _routing_with({str(vault / "nope"): "personal"})
    ctx = detect_context(vault / "elsewhere", routing=routing)
    assert ctx is None


def test_detect_context_does_not_match_partial_segment(vault: Path) -> None:
    """``/dev/work-foo`` must NOT match a rule for ``/dev/work``."""
    from ghostbrain.profile.claude_md import detect_context
    routing = _routing_with({str(vault / "dev" / "work"): "work"})
    ctx = detect_context(vault / "dev" / "work-foo", routing=routing)
    assert ctx is None


def test_filter_by_context_extracts_only_target_section() -> None:
    from ghostbrain.profile.claude_md import filter_by_context
    body = (
        "# Current projects\n\n"
        "## work\n"
        "- Helix work\n"
        "- DLQ triage\n\n"
        "## consulting\n"
        "- Hive\n"
        "- Ghost Brain\n\n"
        "## personal\n"
        "- cooking\n"
    )
    work = filter_by_context(body, "work")
    consulting = filter_by_context(body, "consulting")

    assert "Helix work" in work
    assert "DLQ triage" in work
    assert "Hive" not in work
    assert "cooking" not in work

    assert "Hive" in consulting
    assert "Ghost Brain" in consulting
    assert "Helix work" not in consulting


def test_filter_by_context_case_insensitive() -> None:
    from ghostbrain.profile.claude_md import filter_by_context
    body = "## Work\n- thing\n\n## consulting\n- other\n"
    out = filter_by_context(body, "work")
    assert "thing" in out


def test_filter_by_context_missing_section_returns_empty() -> None:
    from ghostbrain.profile.claude_md import filter_by_context
    body = "## consulting\n- only one section\n"
    assert filter_by_context(body, "work") == ""


def test_generate_claude_md_writes_full_profile(vault: Path, tmp_path: Path) -> None:
    from ghostbrain.profile.claude_md import generate_claude_md

    project = tmp_path / "project-x"
    project.mkdir()
    (project / "package.json").write_text('{"name": "x"}')

    routing = _routing_with({str(project): "consulting"})

    # Replace placeholder profile content with concrete sections so we can
    # assert their presence.
    (vault / "80-profile" / "working-style.md").write_text(
        "# Working style\nDirect, terse.\n"
    )
    (vault / "80-profile" / "preferences.md").write_text(
        "# Preferences\nNo emoji.\n"
    )
    (vault / "80-profile" / "current-projects.md").write_text(
        "# Current projects\n\n## work\n- Helix\n\n## consulting\n- Hive\n"
    )
    (vault / "20-contexts" / "consulting").mkdir(parents=True, exist_ok=True)
    (vault / "20-contexts" / "consulting" / "_profile.md").write_text(
        "# Consultancy profile\nShip CLI is canonical.\n"
    )

    out = generate_claude_md(project, routing=routing)
    body = out.read_text()

    assert out == project / "CLAUDE.md"
    assert "Direct, terse." in body
    assert "No emoji." in body
    assert "Ship CLI is canonical." in body
    assert "Hive" in body
    # The other context's projects must not leak in.
    assert "Helix" not in body
    # Auto-generated header is present.
    assert "Auto-generated by ghostbrain" in body


def test_generate_claude_md_falls_back_when_no_context(vault: Path, tmp_path: Path) -> None:
    """If routing has no rule for the project, full current-projects is emitted
    and the per-context _profile.md is skipped."""
    from ghostbrain.profile.claude_md import generate_claude_md

    project = tmp_path / "elsewhere"
    project.mkdir()

    (vault / "80-profile" / "current-projects.md").write_text(
        "# Current projects\n\n## work\n- A\n\n## consulting\n- B\n"
    )

    out = generate_claude_md(project, routing={"claude_code": {"project_paths": {}}})
    body = out.read_text()

    assert "## work" in body
    assert "## consulting" in body
