"""What the design agents should know about the session's project.

A project in the registry is mostly a name and a folder; what the meeting
means by it usually lives elsewhere in the vault (a synced synopsis, earlier
meetings, docs). The brief is the project's own notes plus the closest vault
search hits for its name, capped so it fits a prompt. Built once per
project per session; never raises.
"""
from __future__ import annotations

import logging
import os
from collections.abc import Callable
from pathlib import Path
from typing import Any

log = logging.getLogger("ghostbrain.design.project_brief")

MAX_CHARS = 24_000
NOTE_MAX_CHARS = 6_000
SEARCH_LIMIT = 8
MIN_SCORE = 0.3
# Generated by the design session itself: never context.
_SKIP_PARTS = {"prototypes", "artefacts"}
_FILLER = {"the", "a", "an", "at", "of", "and", "in", "on", "for", "to"}
# Only the project's own context, and only folders of the user's own
# writing: inbound messages (mail, chat, tickets) are other people's words —
# they would be instructions in a prompt that edits code — and other
# contexts (work clients) must not leak into this project's artefacts.
_ALLOWED_FOLDERS = {"projects", "gdrive", "calendar", "notes", "confluence", "claude", "docs", "jots"}

Search = Callable[..., dict]


def _default_search(q: str, limit: int = 10, days: int | None = None) -> dict:
    from ghostbrain.api.repo import search

    return search.search(q, limit=limit, days=days)


def _keyword_hits(vault: Path, name: str, context: str, limit: int = SEARCH_LIMIT) -> list[dict]:
    """Notes that mention ``name`` verbatim (any case), best first: file name
    matches, then notes outside the raw inbox. Used when semantic search is
    unavailable or finds nothing."""
    import re
    import subprocess

    roots = [f"20-contexts/{context}/{d}" for d in sorted(_ALLOWED_FOLDERS)
             if (vault / "20-contexts" / context / d).is_dir()]
    if not context or not roots:
        return []
    try:
        proc = subprocess.run(
            ["grep", "-rliF", "--include=*.md", "--exclude-dir=.git",
             "--exclude-dir=prototypes", "--exclude-dir=artefacts", "-e", name, "--", *roots],
            cwd=str(vault), capture_output=True, text=True, timeout=30, check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as e:
        log.info("project brief keyword search failed: %s", e)
        return []
    words = [w for w in re.split(r"[^a-z0-9]+", name.lower()) if w and w not in _FILLER] or [name.lower()]

    def names_it(rel: str) -> bool:
        stem = re.sub(r"[^a-z0-9]+", " ", Path(rel).stem.lower())
        return all(re.search(rf"\b{re.escape(w)}", stem) for w in words)

    found = {line.removeprefix("./") for line in proc.stdout.splitlines()}
    # File names too: a synced "garden-of-the-moon---synopsis"
    # may never spell the name out the same way in its text.
    for dirpath, dirnames, filenames in (w for r in roots for w in os.walk(vault / r)):
        dirnames[:] = [d for d in dirnames if not d.startswith(".") and d not in _SKIP_PARTS]
        for f in filenames:
            if f.endswith(".md"):
                rel = os.path.relpath(os.path.join(dirpath, f), vault)
                if names_it(rel):
                    found.add(rel)
    ranked = []
    seen_names: set[str] = set()
    for rel in found:
        ranked.append((0 if names_it(rel) else 1, rel.startswith("00-inbox/"), rel))
    out = []
    for _, _, rel in sorted(ranked):
        base = Path(rel).name
        if base in seen_names:  # the same synced file in the inbox and its context
            continue
        seen_names.add(base)
        out.append({"path": rel, "title": Path(rel).stem, "score": 1.0})
        if len(out) >= limit:
            break
    return out


def _body(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            text = text[end + 4:]
    return text.strip()


def _usable(vault: Path, rel: str, context: str) -> Path | None:
    if not rel or rel.startswith("/") or ".." in Path(rel).parts:
        return None
    parts = Path(rel).parts
    if _SKIP_PARTS & set(parts):
        return None
    if len(parts) < 4 or parts[0] != "20-contexts" or parts[1] != context or parts[2] not in _ALLOWED_FOLDERS:
        return None
    p = vault / rel
    try:
        real = p.resolve()
        if vault.resolve() not in real.parents or not real.is_file():
            return None
    except OSError:
        return None
    return p


def build(project: dict[str, Any] | None, *, search: Search | None = None) -> str:
    """The brief for ``project`` (a registry dict), or "" without one."""
    if not project:
        return ""
    from ghostbrain.paths import vault_path

    vault = vault_path()
    name = str(project.get("name") or project.get("slug") or "").strip()
    parts = [f"# Project: {name}"]
    description = str(project.get("description") or "").strip()
    if description:
        parts.append(description)
    seen: set[str] = set()

    context = str(project.get("context") or "")

    def add(rel: str, title: str) -> None:
        p = _usable(vault, rel, context)
        if p is None or rel in seen:
            return
        body = _body(p)
        if not body:
            return
        seen.add(rel)
        parts.append(f"## {title} ({rel})\n{body[:NOTE_MAX_CHARS]}")

    folder = vault / "20-contexts" / str(project.get("context") or "") / "projects" / str(project.get("slug") or "")
    if folder.is_dir():
        for p in sorted(folder.rglob("*.md")):
            rel = p.relative_to(vault).as_posix()
            add(rel, p.stem)
    if name:
        try:
            hits = (search or _default_search)(name, limit=SEARCH_LIMIT).get("items") or []
        except Exception as e:  # noqa: BLE001 — no index or no embedder: fall back below
            log.info("project brief search for %r failed: %s", name, e)
            hits = []
        hits = [h for h in hits if float(h.get("score") or 0.0) >= MIN_SCORE]
        if not hits:
            hits = _keyword_hits(vault, name, context)
        for hit in hits:
            add(str(hit.get("path") or ""), str(hit.get("title") or "note"))
    brief = "\n\n".join(parts)
    return brief[:MAX_CHARS]
